### ISSUE TITLE
ibrun "%options"

### ISSUE THREAD

**Issue by ponomarevsy** [glennklockwood/sdsc-ibrun#1]
Hi @glennklockwood,

Thank you for providing the ibrun wrapper. I am trying to run the "namd/2.12-verbs" module (NAMD for InfiniBand via OpenFabrics OFED, not for Omni-Path, no MPI needed) on our cluster. It seems to require the ibrun wrapper, so I have downloaded your script. I am getting these errors when submitting the job:

$ **charmrun +p32 ++mpiexec ++remote-shell mympiexec namd2 minimization_1.conf 2>&1 1>minimization_1_regular.log**

Where mympiexec is a script which calls to ibrun:
```
$ more mympiexec
#!/bin/bash

shift; shift; exec /path-to-NAMD/minimization/ibrun $*
```
**Variable "%options" is not imported at /path-to-NAMD/minimization/ibrun line 699.
...
Global symbol "%options" requires explicit package name at /path-to-NAMD/minimization/ibrun line 699.
...
Execution of /path-to-NAMD/minimization/ibrun aborted due to compilation errors.
Charmrun> error attaching to node '127.0.0.1':
Timeout waiting for node-program to connect**

Should I specify some options for ibrun in my namd charmrun command? Thank you in advance!

**Comment by glennklockwood** [comment]
I really don't know.  This ibrun script is not a standard tool and was meant specifically for use at SDSC, so you might be better off either asking whoever maintains your cluster and/or the NAMD module you're using.

Sorry!

**Comment by ponomarevsy** [comment]
Not a problem, @glennklockwood. I think I've figured it out how to run NAMD without the ibrun script. Thanks for your quick reply!

**Comment by kosar7** [comment]
Hello...
Also I have a big problem in compiling "infiniband version" of  NAMD. 
May I ask u help me to solve my problem?
 ```
_./build charm++ verbs-linux-x86_64 --with-production
  cd verbs-linux-x86_64/tests/charm++/megatest
  make pgm
```
  

> ./charmrun ++mpiexec +p4 ./pgm   (uses mpiexec to launch processes)_

for last comment I get below error;
```
Charmrun> scalable start enabled. 
Charmrun> IBVERBS version of charmrun
Charmrun> error attaching to node '127.0.0.1':
Socket closed before recv.

```
I tried to used below command to resolve it, however they did not help;

> sudo apt-get install libopenmpi-dev openmpi-bin openmpi-doc
> sudo apt-get install libibverbs-dev

after long time googling, I found below link about this problem;
`https://www.ks.uiuc.edu/Research/namd/mailing_list/namd-l.2012-2013/2646.html`

 I used  

> grep `hostname` /etc/hosts
and received;

> 127.0.1.1	kosar-P55A-UD3

I do not know what I should to do...
Any help is appreciated.
Best 
Kosar
